ARG NAME
ARG TAG=latest
FROM ${NAME}_conda:${TAG}

# New build stage, so need to redeclare NAME
ARG NAME
COPY docker/${NAME}/start.sh ./start.sh

SHELL ["/bin/bash", "-c"]

CMD source activate service && bash ./start.sh
