ARG BASE_IMAGE=ndif_base
ARG TAG=latest
FROM ${BASE_IMAGE}:${TAG}

# Update environment with service-specific dependencies
ARG NAME
COPY src/services/${NAME}/environment.yml .

RUN conda env update --name service -f environment.yml