ARG BASE_IMAGE=ndif_base
ARG TAG=latest
FROM ${BASE_IMAGE}:${TAG}

# Install service-specific package
ARG NAME
COPY ndif-${NAME} ./ndif-${NAME}

# Install service-specific package (mainly for dependencies)
RUN conda run --name service pip install -e ./ndif-${NAME}