ARG NAME
FROM ${NAME}_conda:latest

# New build stage, so need to redeclare NAME
ARG NAME
COPY ./src.tar.gz ./src.tar.gz
COPY services/${NAME}/start.sh ./start.sh

RUN tar -xvf ./src.tar.gz \
    && rm ./src.tar.gz

CMD source activate service && bash ./check_and_update_env.sh && bash ./start.sh