channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - pip:
    - git+https://github.com/ndif-team/nnsight@dev
    - pytest
    - pytest-order
    - pytest-dependency
    - influxdb-client
    - pyyaml