# Prometheus config file.

# NOTE: Prometheus does not support environment variables, so changes made to the service ports for Ray and FastAPI metrics need to be reflected here!

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'combined_metrics' # Merges metrics from FastAPI and Ray together (needed for Grafana to group metrics from a single request together).
    static_configs:
      - targets: 
        - localhost:5000  # FastAPI - Prod
        - localhost:5001 # FastAPI - Dev
    file_sd_configs:
      - files:
        - '/tmp/ray/prom_metrics_service_discovery.json' # Contains dynamically updated list of ports & IP addresses of all the Ray nodes.
    metrics_path: /metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'ray_request_status'
        target_label: __name__
        replacement: 'request_status'
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*:(8267|5000|5001)' # Metric export ports for FastAPI and Ray services
        replacement: '${1}'
        target_label: job
        action: replace
      - source_labels: [job]
        regex: '8267'
        replacement: 'ray'
        target_label: job
      - source_labels: [job]
        regex: '5000' # Prod
        replacement: 'fast_api'
        target_label: job
      - source_labels: [job]
        regex: '5001' # Dev
        replacement: 'fast_api'
        target_label: job
