services:
  api:
    command: ["bash", "./src/nns_inst.sh"]
    volumes:
      - ../../docker/helpers/nns_inst.sh:/src/nns_inst.sh
      - ${NNS_PATH}:/nnsight

  ray-head:
    command: ["bash", "./src/nns_inst.sh"]
    volumes:
      - ../../docker/helpers/nns_inst.sh:/src/nns_inst.sh
      - ${NNS_PATH}:/nnsight
